plugins:
  - node
extends: xo
env:
  node: true
  commonjs: true
  es6: true
parserOptions: 
  ecmaFeatures: 
    jsx: false
    experimentalObjectRestSpread: false
  ecmaVersion: 2016
  sourceType: script
rules:
  
  # possible errors
  eqeqeq:
    - error
    - smart
  no-console:
    - warn
  no-confusing-arrow:
    - error
  no-eq-null:
    - "off"
  no-use-before-define:
    - error
    - functions: false
      classes: false
  node/no-unsupported-features:
    - error
    - version: 4
  no-var:
    - error
  strict:
    - error
    - safe

  # styling
  arrow-body-style:
    - error
    - as-needed
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  indent:
    - error
    - 2
  lines-around-directive:
    - error
    - always
  newline-after-var:
    - error
    - always
  object-shorthand:
    - error
  one-var:
    - error
    - initialized: never
      uninitialized: always
  padded-blocks:
    - "off"
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  prefer-const:
    - error
  space-before-function-paren:
    - error
    - never
  valid-jsdoc:
    - error
    - requireParamDescription: true
      requireReturnDescription: false
      requireReturn: false
